Updating dialogTitle prop to be a string or element
Yuvaleros/material-ui-dropzone pull request #234
Opened 2020-08-11 09:50 UTC by 4-Eyes

## Description

* Adding the ability to customise the dialog title with JSX, rather than it just being a string.

## Type of change

- New feature (non-breaking change which adds functionality)

## How Has This Been Tested

- [ ] Adding to the documentation page for the `DropzoneDialogBase` an example that includes a custom dialog title with an 'x' button for closing the dialog.

**Test Configuration**:

- Browser: Chrome Version 84.0.4147.105

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2020-08-24 09:21 UTC, panz3r requested changes
Hi @4-Eyes ,

Thanks for your contribution and sorry for the delayed answer.

I added some comments and I'd ask you to also update TS typings to match the changes.

2020-08-24 09:21 UTC, panz3r commented on .gitignore
> +.vscode
Do not commit this file

2020-08-24 09:21 UTC, panz3r commented on .size-snapshot.json
>          "code": 10819,
Do not commit this file

2020-08-24 09:21 UTC, panz3r commented on dist/index.es.js
>     * Props to pass to the Material-UI Dialog components.
Do not commit this file

2020-08-24 09:21 UTC, panz3r commented on dist/index.es.js.map
> +{"version":3,"file":"index.es.js","sources":["../src/helpers.js","../src/components/PreviewList.js","../src/components/SnackbarContentWrapper.js","../src/components/DropzoneAreaBase.js","../src/compo
Do not commit this file

2020-08-24 09:21 UTC, panz3r commented on dist/index.js
>     * Props to pass to the Material-UI Dialog components.
Do not commit this file

2020-08-24 09:21 UTC, panz3r commented on dist/index.js.map
> +{"version":3,"file":"index.js","sources":["../src/helpers.js","../src/components/PreviewList.js","../src/components/SnackbarContentWrapper.js","../src/components/DropzoneAreaBase.js","../src/componen
Do not commit this file

2020-09-11 20:16 UTC, 4-Eyes commented
Apologies for the slow response. I believe I've addressed all your comments.

2020-09-15 08:55 UTC, panz3r approved these changes
LGTM 👍 

@4-Eyes , thanks for your contribution, now it looks good but unfortunately GitHub says I cannot merge it because of conflicts, can you please rebase your changes (only the revenant ones) onto `master` and update this PR?
Thanks again

2020-09-19 09:08 UTC, 4-Eyes commented
@panz3r the PR should be updated now.

2020-09-20 12:37 UTC, panz3r approved these changes
LGTM 👍

2020-09-20 12:37 UTC, merged