feat: improves onDelete, dropzoneText and docs
Yuvaleros/material-ui-dropzone pull request #324
Opened 2021-09-16 22:27 UTC by jpinho

## Description

This PR adds 3 contributions:

- **New Feature (extension/non-breaking):** Improving onDelete of the DropzoneArea to make it more useful
- **New Feature (extension/non-breaking):** Improving dropzoneText to make it more flexible
- **Docs:** Improving docs, killing the screenshots in favor of an animated GIF

## How Has This Been Tested

All of the changes done here have been tested on a project consuming my fork version.
Both `onDelete` and dropzoneText using react elements seem to work fine.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-17 08:07 UTC, jpinho commented
can you give this a look please @panz3r?

2021-11-06 17:41 UTC, panz3r requested changes
Hi @jpinho ,

Thanks for your contributions and sorry for the delayed review.

Just a couple of changes (mostly related to docs files) and I can merge your PR.

2021-11-06 17:41 UTC, panz3r commented on README.md
>  # material-ui-dropzone
Revert changes to `README.md` or exclude them from this PR.

2021-11-06 17:41 UTC, panz3r commented on docs/intro.md
>  # material-ui-dropzone
Revert changes to `docs/intro.md` or exclude them from this PR.

2021-11-06 17:41 UTC, panz3r commented on docs/screenshots.md
> -This is the Dialog component:
Revert changes to `docs/screenshots.md` or exclude them from this PR.

2021-11-06 17:41 UTC, panz3r commented on styleguide.config.js
> +      name: 'Demo',
Revert this change

2021-11-15 00:19 UTC, jpinho commented
Thanks for the review. I've seen it before, but just got from holidays. Will be addressing this the upcoming week.

2026-03-29 18:43 UTC, closed without merging